### ISSUE TITLE
Consider ditching rc as its not being maintained

### ISSUE THREAD

**Issue by JimmyBjorklund** [rexxars/registry-auth-token#39]
rc is outdated and have security issue, consider replacing it with some of your own code making the packet free from dependanies.

**Comment by rexxars** [comment]
There's quite a bit of logic involved in resolving `.npmrc` and it's values. Do you know what npm uses internally to read it?

**Comment by rexxars** [comment]
Looks like [libnpmconfig](https://github.com/npm/libnpmconfig) is what it's using under the hood.

**Comment by JimmyBjorklund** [comment]
It uses ini, this is available in 2.0.0

**Comment by bwbuchanan** [comment]
+++

The unmaintained rc package was recently [compromised](https://github.com/advisories/GHSA-g2q5-5433-rhrf) on npm.

It would be great if this dependency could be eliminated. At a minimum, unmaintained dependencies ought to be pinned to an exact version number to help mitigate supply chain attacks.

**Comment by silverwind** [comment]
I would suggest just to drop the `rc` dependency and require user to pass in the `npmrc` object, obtained either from `ini` or `libnpmconfig` or other mechanisms.

**Comment by rexxars** [comment]
> I would suggest just to drop the rc dependency and require user to pass in the npmrc object, obtained either from ini or libnpmconfig or other mechanisms.


I'd like to automatically load it, to be honest. But would be happy to take a PR that does not change the API.

**Comment by silverwind** [comment]
Sounds good as well, but I guess some investigation in how npm currently loads its config will be necessary. [`libnpmconfig`](https://github.com/npm/libnpmconfig) is deprecated and there is [`@npmcli/config`](https://github.com/npm/config) but I fail to see how one would use it or if it's the right module for the job.

**Comment by Kytech** [comment]
Was just looking at using `@npmcli/config` to do the exact thing this package is doing before I managed to come across this. `@npmcli/config` alone does not ship everything you'd need to be able to read the npm config values, though it does appear to contain the file resolution logic. The problem is that the `Config` constructor appears to need some information from this file: https://github.com/npm/cli/blob/latest/lib/utils/config/index.js, with a few slight changes, to get past the `declarations is undefined` error, and that file is not accessible externally (I had to `npm install npm`, then delete the `exports` key in `node_modules/npm/package.json` to get access to this while I was testing this).

The fact that `declarations` needed to be specified was not detailed in the usage for `@npmcli/config`, so I figured it had to be somewhere in npm itself. I was able to confirm that the config information would indeed be provided with the following snippet that pulled in the relevant files from npm (after hacking on package.json):

```js
const Config = require('@npmcli/config');
const path = require('path');

const conf = new Config({ npmPath: path.resolve('.'), types: Config.typeDefs, ...npmConfig });
await conf.load();
```

Since the config definitions are not exported, it would probably require manually copying over just the definitions that are needed, but then you'd be able to get the config info using the `@npmcli/config` package. I suspect that it may only need the `registry` option definition, and the `prefix` option definition, since I managed to get it to almost successfully return from conf.load() when giving it an empty object as the value of the definitions property passed to the constructor. It only errored on trying to read the registry URL.

The only other option I can think of would be to just pull in a known good version of `rc` and keep a copy of it in this repository and maintain what we need of it going forward. However, if I can figure out that last hurdle for using `@npmcli/config`, that may be our better option since it's published directly from npm, so we shouldn't need to worry about the package going unmaintained.

**Comment by silverwind** [comment]
Maybe it'd be worth asking npm to provide a easy-to-use export of the config, like `libnpmconfig` did. Other tools [are facing the same issue](https://github.com/raineorshine/npm-check-updates/issues/1108).

**Comment by Kytech** [comment]
Yeah, regardless of what I find tinkering with `@npmcli/config`, I had been thinking it would be good to bring this to the attention of NPM.

**Comment by Kytech** [comment]
Another option would be possibly using pnpm's npm configuration reading package: [`@pnpm/npm-conf`](https://github.com/pnpm/npm-conf). This seems purpose-built for reading just npm configuration and it comes from a well-known project, which should give us a viable alternative to rc. If I get the time, I'll have to tinker with this a bit. Been short on time since I just transitioned jobs.

**Comment by Kytech** [comment]
Can confirm that pnpm's package can pull the config info in a similar manner as rc. May need to adjust how we deal with defaults just a bit, but otherwise, I think this won't be hard to implement. I'll probably create a fork and PR for this change since it should be fairly straightforward.

**Comment by rexxars** [comment]
> Can confirm that pnpm's package can pull the config info in a similar manner as rc. May need to adjust how we deal with defaults just a bit, but otherwise, I think this won't be hard to implement. I'll probably create a fork and PR for this change since it should be fairly straightforward.

Thanks, that seems like a good way forward!

**Comment by Kytech** [comment]
@rexxars I've created a PR to replace `rc` with `@pnpm/npm-conf`. It is ready for your review and we can discuss any changes over on that PR.

**Comment by rexxars** [comment]
Thanks to @Kytech, v5.0.1 is now using `@pnpm/npm-conf` instead of `rc`! Note that the minimum node version required is now v14.

**Comment by silverwind** [comment]
Had some attempts at integrating [`@pnpm/npm-conf`](https://github.com/pnpm/npm-conf) in another project and I think it's not a ideal replacement to `rc`:

1. It messes with `require.resolve` which makes it incompatible with ESM.
2. It's API is needlessly complex with that `.get` instead of just exposing a plain object.
3. It has more dependencies than it needs.  t depends on [`config-chain`](https://github.com/dawsbot/config-chain) which ironically recommends switching to `rc`.

I think the proper solution is likely to just rewrite `rc` to a simple dependency-less module, probably ESM only.

**Comment by Kytech** [comment]
> 1. It messes with `require.resolve` which makes it incompatible with ESM.
 
**EDIT:** This package works when used in an ESM module. See comment below for confirmation.

Original comment:

Correct me if I am wrong here, but doesn't node support CJS <-> ESM interop such that a CJS module can be imported in an ESM node app, meaning that the use of `require.resolve` in `@pnpm/npm-conf` shouldn't be an issue? (https://nodejs.org/api/esm.html#interoperability-with-commonjs).

~~I can add a test that calls this package from an ESM script if we're concerned about this project not supporting ESM because of this, or we may just need to provide a `module` export that handles the interop to prevent such issues, just to make sure we have our bases covered. My understanding is that this shouldn't be an issue unless there's something wrong with node's own ESM interop, which should probably be reported upstream in that case.~~

> 2. It's API is needlessly complex with that `.get` instead of just exposing a plain object.

I agree with this, but it's much better than `@npmcli/config`, which has a very complex set of parameters that we would have to pass to get it to even function at all. Considering that one of the original ideas was to utilize config resolution logic used by the package manager itself, using PNPM's library seems to get us as close to that as possible without dealing with the awful API exposed by NPM's own package since PNPM's package uses a common dependency as NPM for config resolution. Granted, the API exposed by NPM's own `@npmcli/config` also uses `.get()` due to the shared dependency, so if we want to use what NPM uses, we're kind of stuck with this API, though it at least mirrors something else that is built in to JS as `Map`s have to use `.get()` for reading values.

If we really want to make the API look like regular object access, we can always wrap the call to `npmConf` (exported by pnpm's package) with a helper that attaches a proxy which converts all property access attempts to undefined properties to a call to `.get()` and call that wrapper instead if the API style is too complex. I initially thought about this when making the PR, but I felt that it added too much extra complexity and hand-wavy-ness to the codebase and obscured how pnpm's package was actually used. The use of `.get()` mirrors the built-in `Map` object as far as reading values is concerned, so it doesn't feel like it introduces a significant degree of added complexity. There could be a technical reason for this behavior, as the built-in `Map` can't just use plain object property syntax. However, if we really want to see that wrapper implemented, I'd be happy to submit a PR with that wrapper added.

> 3. It has more dependencies than it needs.  t depends on [`config-chain`](https://github.com/dawsbot/config-chain) which ironically recommends switching to `rc`.

I did see this when looking into PNPM's package, though I still decided it was worth looking into and trying to implement. I'll explain my thought process on that here for other maintainers to determine if it falls in line with the goals of the issue:

`config-chain` looks to be archived more as a feature freeze for the sake of `npm` since it's what NPM itself has used (this is the common dependency I referred to earlier). However, since this is what NPM has been using, it keeps us on the same code path for config resolution, which appears to be one of the outcomes we'd like to see from moving away from rc. (though it seems NPM might be starting to move away from this with the introduction of their `@npmcli/config` package, looking into the return values of this package shows that it appears to be similar to the config-chain package anyway since the objects returned from both NPM's package an PNPM's package are extremely similar in their shape, structure, and API usage. `@npmcli/conf`'s  predecessor, `libnpmconfig`, declared config-chain as a dependency). The alternative to PNPM's package of using and maintaining a copy of the abandoned rc library ourselves has the downside of being a very different code path from what NPM has been using for config resolution. This also increases the amount of code this project has to maintain. What ultimately made using PNPM's package feel like a better option was because of how the maintenance burden on this project of responding to changes is avoided because of how active the PNPM project is.

Since the PNPM project is very active and has a large number of contributors, I would think that they would update/transition dependencies as needed in the event that NPM ever makes significant changes to their configuration system (such as if config-chain's logic no longer mirror's NPM's own logic). I would think that if using config-chain is not sufficient in the future, they would do the work of actively maintaining their own modified version of it or figure out how to use NPM's `@npmcli/config` package. As it currently stands though, it looks like NPM has, and continues to use, `config-chain`-based logic to resolve configurations.

Additionally, the primary maintainer or of PNPM's config package happens to be the person who created [issue 14]( https://github.com/rexxars/registry-auth-token/issues/14) on this repo. Judging on what they said in that issue, PNPM themselves avoided `rc` and chose the path that they did because they're wanting to mirror NPM's config algorithm as exactly as possible, especially since they really have to get it right being a package manager themselves. With the current state of what npm presently provides for external projects to read configs, it seems like they've determined this to be the best approach. Yarn as of v2 no longer even looks at .npmrc, so they don't have a currently maintained approach as of now, hence why I would think PNPM's approach would be kept well up to date.

> I think the proper solution is likely to just rewrite `rc` to a simple dependency-less module, probably ESM only.

As I mentioned, ESM compatibility is not broken by PNPM's use of `require.resolve`, which eliminates what looks to me to be the largest reason for switching to a re-written version of `rc` that this project would maintain. This option was discussed earlier in the issue, but I'm under the impression that the desire would be to use something that is more in line with what NPM itself uses. Since PNPM's package and NPM's own config package both either directly depend on or are based off of `config-chain`, using PNPM's package looks to get us to the same configuration logic as NPM's package without having to deal with an even worse API. If we really want to make it so we don't have to call `.get()` and instead we can just use object property syntax, there's always the option of wrapping the call to PNPM's package so that it attaches a proxy that I detailed above.

There's an additional disadvantage of dropping PNPM's package. PNPM's package is much more robust in that support for any npm configuration environment variables and command-line flags passed to any npm commands are handled with no additional effort on the package consumer. ~~If the main concern is ESM compatibility, perhaps maintaining a copy of PNPM's package re-written as ESM (require.resolve can be used from ESM in node with the `module.createRequire` function https://nodejs.org/docs/latest-v14.x/api/module.html#module_module_createrequire_filename in Node 12+. Usage example: https://stackoverflow.com/a/62499498/7452727), or finding and submitting an upstream PR of the needed fix would be more ideal. I would think that maintaining a fork of an active package can be easier than maintaining a copy of an abandoned package since we'd benefit from upstream activity with something more active.~~

**Comment by Kytech** [comment]
Update: Can confirm that PNPM's use of `require.resolve` will not cause this package to break compatibility with ESM consumers. I threw together a quick test that ensures the package is still functioning when imported into an ESM environment:
```
  ESM Support
    ✔ should be running this test in an ESM context without require.resolve
    bearer token
      ✔ should return auth token if registry is defined
```
Link to test: https://github.com/Kytech/registry-auth-token/blob/76ad6a4cd806b703c0dfb11d843b609bf416ae72/test/esm-support.test.mjs Tested against node 14

I'd be happy to open a PR to add this test file to the test suite if we feel it is needed.

I also tried directly importing and using `@pnpm/npm-conf` into a .mjs ESM module and it worked fine on node 14 using the built-in ESM <-> CJS interop, so PNPM's package looks to be compatible with ESM imports on node without any issue. (This was just a scratch file, not in the linked file.)
